### ISSUE TITLE
list with primitive types doesn't work

### ISSUE THREAD

**Issue by Achilles718611** [wallneradam/esorm#16]
List with primitive type doesn't work.
```
ids = list[int]
ids = list[str]
ids = list[int32]
...
```

It throws the following error.
```
    for name, field_info in model.model_fields.items():
                            ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'str' has no attribute 'model_fields'
```

**Comment by Achilles718611** [comment]
I think Elasticsearch supports arrays.
https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html

**Comment by wallneradam** [comment]
Thank you for reporting this issue. This has been added in the new version (v0.5.1). Please check it.

**Comment by Achilles718611** [comment]
It still doesn't work.

**Comment by wallneradam** [comment]
Oh, I found it, and fixed in v0.5.2. I hope it is good for now.

**Comment by Achilles718611** [comment]
It works with v0.5.2
